version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        MYSQL_HOST: db
        MYSQL_DATABASE: example
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    ports:
      - "8080:80"
    volumes:
      - ./images:/var/www/html/images
  db:
    image: mysql:5.7
    environment:
        MYSQL_DATABASE: example
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_RANDOM_ROOT_PASSWORD: 'root'
    volumes:
      - 'data:/var/lib/mysql'
  adminer:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password

volumes:
  data: